# Generated by Django 4.0.7 on 2022-11-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_first_name_order_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('received', 'Order Received'), ('processing', 'Order Processing'), ('way', 'On the way'), ('completed', 'Order Completed'), ('canceled', 'Order Canceled')], default='received', max_length=50, null=True),
        ),
    ]
